### ISSUE TITLE
load balancing multiple remote chrome browsers

### ISSUE THREAD

**Issue by graingert** [sidorares/crmux#19]
I'd like to be able to run a large number of chrome browsers behind a load balancer.

**Comment by sidorares** [comment]
this library does opposite ( allows to connect multiple clients to single browser )
What you need would probably look similar in some parts: http/ws server on the front with knowledge of backends, on connection it decides which backend to use (round robin maybe) and then just proxies communication 1:1 to that backend. If you happen to find what you need please add as a comment and I'll link it from readme
